erDiagram
    STUDENTS {
        int rfid_key PK "AUTO_INCREMENT"
        varchar(50) first_name "NOT NULL"
        varchar(50) last_name "NOT NULL"
        varchar(20) university_id "UNIQUE NOT NULL"
        varchar(50) university_email "NOT NULL"
        varchar(20) contact_number "NULLABLE"
        varchar(50) course "NOT NULL"
        varchar(100) profile_picture "NULLABLE"
        varchar(20) emergency_contact_num "NULLABLE"
        TIMESTATMPZ created_at "NOT NULL"  
    }