erDiagram
    STUDENTS {
        int student_id PK "PRIMARY KEY"
        varchar(50) first_name "NOT NULL"
        varchar(50) last_name "NOT NULL"
        varchar(20) university_id "UNIQUE NOT NULL"
        varchar(255) university_email "NOT NULL"
        varchar(20) contact_number "NULLABLE"
        varchar(255) profile_picture "NULLABLE"
        varchar(20) emergency_contact_num "NULLABLE"
        TIMESTATMPZ created_at "NOT NULL"  
    }

    LOGS {
        int student_id FK "NOT NULL"
        timestamp time_in "NOT NULL"
        timestamp time_out "NOT NULL"
    }

    STUDENTS||--|{LOGS:"logs onto"
