@baseURL = http://localhost:5198

### Create student
POST {{baseURL}}/api/students
Content-Type: application/json

{
    "RfidUid": "1145133079",
    "FirstName": "Judd Rylee",
    "LastName": "Bahian",
    "UniversityId": "2025-1134790",
    "UniversityEmail": "bahianjc@students.nu-cebu.edu.ph",
    "ContactNumber": null,
    "ProfilePicture": null,
    "EmergencyContactNumber": null
}

### Get student by RFID
GET {{baseURL}}/api/students/rfid/1145133079


### Get all students
GET {{baseURL}}/api/students

### Health check
GET {{baseURL}}/health-check


PUT {{baseURL}}/api/students